name: JavaScript PWA Recipe App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      APP_NAME: "PWA Recipe App"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies (if any)
        run: |
          if [ -f package.json ]; then
            npm install
          fi

      - name: Run linting
        run: npm run lint

      - name: Print Environment Variable
        run: |
          echo "App Name: $APP_NAME"

      - name: Build Project (if any build step exists)
        run: |
          if [ -f package.json ]; then
            npm run build
          fi

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
      - name: Upload logs
        run: |
          mkdir logs
          echo "Logs uploaded on $(date)" > logs/summary.log
          tar -czf logs.tar.gz logs
        continue-on-error: true
